name: Enable Branch Protection

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 6 * * *' # Runs daily at 12 AM CST

jobs:
  enable-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Apply branch protection to all repos
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          OWNER: ${{ secrets.OWNER }}
        run: |
          chmod +x enable_branch_protection.sh
          ./enable_branch_protection.sh

        